### ISSUE TITLE
Validate Purge Process

### ISSUE THREAD

**Issue by NicolasSiver** [akamai/AkamaiOPEN-edgegrid-node#34]
Hello guys,

CCU v3 returns something like this:

```
{  
    "detail": "Request accepted",   
    "estimatedSeconds": 5,   
    "httpStatus": 201,   
    "purgeId": "5f45684a-3d97-11e6-aaa0-73dc7cf18dee",   
    "supportId": "17PY1467163102911830-244184256"  
}  
```

My question is how to validate purge process? I don't see any examples.
It says, that purge will take `5` seconds, how to validate that purge was successful after 5 seconds?

Thanks

**Comment by synedra** [comment]
There is no validation for the purge request in version 3.  If you require a status for the purge, you need to use version 2.

**Comment by NicolasSiver** [comment]
@synedra  What is the probability that purge will take more than `5` seconds?

**Comment by synedra** [comment]
In theory, it could happen.  In practice, I don't believe it does.  If you want the 5 second purge and want to check the status, you can do a HEAD request on one of the URLs to make sure the headers are correct.

**Comment by NicolasSiver** [comment]
Last question ;)
Do you have any plans to add an API to EdgeGrid to validate a purge operation?

**Comment by synedra** [comment]
At this time, because of the mechanism of the purge (it is a pub/sub model where the servers listen for changes) it would be very difficult to verify that all of the edge servers had received and processed the purge request.  In testing, we have found that the purge is very robust and reliable.  I understand that for some customers the status is important, and for that you need to either use version 2 or, as I said, implement your own check using a HEAD request.

**Comment by NicolasSiver** [comment]
Thanks, it was helpful.
